# 工作流名称
name: Hexo Blog Deploy

# 只在push到master分支时的时候启动
on:
  push:
    branches: [ master ]

# 使用ubuntu虚拟机
jobs:
  build:
    
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]
    
    # 工作流步骤
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      
      # 安装Hexo
      - name: Install hexo
        run: |
          npm install hexo-cli -g
          npm install
      
      # 设置SSH密钥，读取GITEE_RSA_PRIVATE_KEY
      - name: Setup private key
        env:
          HEXO_DEPLOY_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh/
          echo "$HEXO_DEPLOY_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          ssh-keyscan gitee.com >> ~/.ssh/known_hosts
      
      # 配置Git设置
      - name: Setup git settings
        run: |
          git config --global user.name 'liuyujun'
          git config --global user.email '1447792228@qq.com'
      
      # 部署
      - name: Deploy hexo
        run: |
          hexo clean
          hexo generate
          hexo deploy
      
      # 同步到Gitee
      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@master
        env:
          # 注意在 Settings->Secrets 配置 GITEE_RSA_PRIVATE_KEY
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
        with:
          # 注意替换为你的 GitHub 源仓库地址
          source-repo: "git@github.com:lyjiii/lyjiii.github.io.git"
          # 注意替换为你的 Gitee 目标仓库地址
          destination-repo: "git@gitee.com:liuyujunzuishuai/liuyujunzuishuai.git"
      
      # 部署Gitee Pages
      - name: Build Gitee Pages
        uses: yanglbme/gitee-pages-action@master
        with:
          # 注意替换为你的 Gitee 用户名
          gitee-username: liuyujunzuishuai
          # 注意在 Settings->Secrets 配置 GITEE_PASSWORD
          gitee-password: ${{ secrets.GITEE_PASSWORD }}
          # 注意替换为你的 Gitee 仓库
          gitee-repo: liuyujunzuishuai/liuyujunzuishuai.git
